---
title: "BET PS data for Stock Synthesis"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output:
  word_document:
    fig_width: 12
    fig_height: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

This example code demonstrates how to compile the purse-seine catch and length composition data for the stock assessment of bigeye tuna in the eastern Pacific Ocean.

```{r load catch data}

library(tidyverse)
save_dir <- "D:/OneDrive - IATTC/IATTC/2022/BSE stuff from Cleridy/BET/"
yr.end <- 2021

BET.OBJ.Catch.20002021 <- read.csv(paste0(save_dir,"BET.OBJ.Catch.20002021.csv"))
BET.OBJ.Catch.19751999 <- read.csv(paste0(save_dir,"BET.OBJ.Catch.19751999.csv"))

BET.NOA.Catch.20002021 <- read.csv(paste0(save_dir,"BET.NOA.Catch.20002021.csv"))
BET.NOA.Catch.19751999 <- read.csv(paste0(save_dir,"BET.NOA.Catch.19751999.csv"))

BET.DEL.Catch.20002021 <- read.csv(paste0(save_dir,"BET.DEL.Catch.20002021.csv"))
BET.DEL.Catch.19751999 <- read.csv(paste0(save_dir,"BET.DEL.Catch.19751999.csv"))
```

```{r process catch data}
Year_OBJ <- data.frame(Year = seq(1,(yr.end-1974)*4),
                       Area = rep(c("A1","A2","A3","A4","A5"), each = (yr.end-1974)*4))

BET_OBJ_Catch <- rbind(BET.OBJ.Catch.19751999,BET.OBJ.Catch.20002021) %>% 
  mutate(Year=(year-1975)*4+quarter) %>%
  gather(3:7,key="Area",value="Catch") %>% 
  select(Year,Area,Catch)
BET_OBJ_Catch <- left_join(Year_OBJ,BET_OBJ_Catch) %>%
  mutate(Catch=ifelse(is.na(Catch),0,Catch),
         Type="OBJ")

Year_NOA <- data.frame(Year = seq(1,(yr.end-1974)*4),
                       Area = rep(c("A1","A2"), each = (yr.end-1974)*4))
BET_NOA_Catch <- rbind(BET.NOA.Catch.19751999,BET.NOA.Catch.20002021) %>% 
  mutate(Year=(year-1975)*4+quarter) %>%
  gather(3:4,key="Area",value="Catch") %>% 
  select(Year,Area,Catch)
BET_NOA_Catch <- left_join(Year_NOA,BET_NOA_Catch) %>%
  mutate(Catch=ifelse(is.na(Catch),0,Catch),
         Type="NOA")

Year_DEL <- data.frame(Year = seq(1,(yr.end-1974)*4),
                       Area = rep(c("A1","A2"), each = (yr.end-1974)*4))
BET_DEL_Catch <- rbind(BET.DEL.Catch.19751999,BET.DEL.Catch.20002021) %>% 
  mutate(Year=(year-1975)*4+quarter) %>%
  gather(3:4,key="Area",value="Catch") %>% 
  select(Year,Area,Catch)
BET_DEL_Catch <- left_join(Year_DEL,BET_DEL_Catch) %>%
  mutate(Catch=ifelse(is.na(Catch),0,Catch),
         Type="DEL")

BET_NOA_Catch$Catch <- BET_NOA_Catch$Catch + BET_DEL_Catch$Catch

BET_PS_Catch <- rbind(BET_OBJ_Catch,BET_NOA_Catch)
write.csv(BET_PS_Catch,file=paste0(save_dir,"BET_PS_Catch_1975-",yr.end,".csv"),row.names = FALSE)
```

```{r plot catch data}
ggplot(data=BET_PS_Catch) +
  geom_line(aes(x=Year,y=Catch,color=Type)) +
  facet_wrap(~Area,nrow=5,scales = "free") +
  geom_vline(xintercept = 100.5,linetype = "dashed") +
  theme_bw(16)
```

```{r load comp data}
BET.OBJ.Comp.20002021 <- read.csv(paste0(save_dir,"BET.OBJ.Comp.20002021.csv"))
BET.OBJ.Comp.19751999 <- read.csv(paste0(save_dir,"BET.OBJ.Comp.19751999.csv"))

BET.NOA.Comp.20002021 <- read.csv(paste0(save_dir,"BET.NOA.Comp.20002021.csv"))
BET.NOA.Comp.19751999 <- read.csv(paste0(save_dir,"BET.NOA.Comp.19751999.csv"))

# BET.DEL.Comp.20002021 <- read.csv(paste0(save_dir,"BET.DEL.Comp.20002021.csv"))
# BET.DEL.Comp.19751999 <- read.csv(paste0(save_dir,"BET.DEL.Comp.19751999.csv"))
```

```{r process comp data}
BET_OBJ_Comp <- rbind(BET.OBJ.Comp.19751999,BET.OBJ.Comp.20002021) %>%
    mutate(Year=(year-1975)*4+quarter, Type="OBJ") %>%
  arrange(area,Year)
BET_OBJ_Comp <- BET_OBJ_Comp[c(207,206,3:205)]

BET_NOA_Comp <- rbind(BET.NOA.Comp.19751999,BET.NOA.Comp.20002021) %>%
    mutate(Year=(year-1975)*4+quarter, Type="NOA") %>%
  arrange(area,Year)
BET_NOA_Comp <- BET_NOA_Comp[c(207,206,3:205)]

BET_PS_Comp <- rbind(BET_OBJ_Comp,BET_NOA_Comp)

# process PS LF data
names(BET_PS_Comp)[5:205] <- 1:201

Nwells <- BET_PS_Comp %>% select(Type,Year,area,nwells)
  
BET_PS_Comp_Long <- BET_PS_Comp %>% gather(5:205,key="l",value="lf") %>%
  mutate(L=cut(as.numeric(l), breaks = c(seq(20,198,2), Inf), right=F, labels = seq(20,198,2))) %>% na.omit() %>%
  select(Type,Year,area,L,lf) %>%
  group_by(Type,area,Year,L) %>%
  summarise(LF=sum(lf))

BET_PS_Comp_Short <- BET_PS_Comp_Long %>%
  spread(L,LF)

BET_PS_Comp_Final <- left_join(BET_PS_Comp_Short,Nwells)

BET_PS_Comp_SS <- data.frame("Type" = BET_PS_Comp_Final$Type,
                             "Year" = BET_PS_Comp_Final$Year,
                             "Month" = 1,
                             "Fleet" = BET_PS_Comp_Final$area,
                             "Sex" = 0,
                             "Part" = 0,
                             "Nsamp" = BET_PS_Comp_Final$nwells)

BET_PS_Comp_SS <- cbind(BET_PS_Comp_SS, BET_PS_Comp_Final[,4:93], BET_PS_Comp_Final[,4:93])
  
write.csv(BET_PS_Comp_SS,file=paste0(save_dir,"BET_PS_Comp_1975-",yr.end,".csv"),row.names = FALSE)
```

```{r plot comp data}
names(BET_PS_Comp)[5:205] <- 1:201
BET_PS_Comp_mean <- BET_PS_Comp %>%
  gather(5:205,key="Length",value=comp) %>%
  group_by(Type,area,Length) %>%
  summarise(Comp=sum(comp*nwells)) %>%
  group_by(Type,area) %>%
  mutate(Length=as.numeric(Length),Comp=Comp/sum(Comp))

ggplot(data=BET_PS_Comp_mean) +
  geom_line(aes(x=Length,y=Comp,color=Type)) +
  facet_wrap(~area,nrow = 3) +
  theme_bw(16)
```
