library(BSE)
# global setup
raw_data_dir <- "D:/OneDrive - IATTC/IATTC/2022/BSE stuff from Cleridy/single spp programs_PS_1975-1999/Raw data extractions/"
save_dir <- "D:/OneDrive - IATTC/IATTC/2022/BSE stuff from Cleridy/BET/"
yr.start <- 1975
yr.end <- 1987
Species <- "BET"
# grow.increments <- grow.increments.betyftskj # the growth increment matrix

# Load the base files generated by Cleridy
load("D:/OneDrive - IATTC/IATTC/2022/BSE stuff from Cleridy/single spp programs_PS_1975-1999/Raw data extractions/base files_1975-1999_for SAC 2020.RData")

# Running BET OBJ
PS <- "OBJ"

# area.substitution.mat <- area.substitution.mat.BET.movemodel.ALL # for OBJ

cae.stratflg <- create.strat.flg.f(cae$latc5,cae$lonc5,is.lwrght=F,cae$month,cae$setype,cae$class,PS=PS,Species=Species)
check.strat.flg.f(cae$latc5,cae$lonc5,cae.stratflg)
# 
# lfgrpd.stratflg <- create.strat.flg.f(lfgrpd$lat.5deg,lfgrpd$lon.5deg,is.lwrght=T,floor(lfgrpd$moda/100),lfgrpd$setype,lfgrpd$class,PS=PS,Species=Species)
# check.strat.flg.f(lfgrpd$lat.5deg,lfgrpd$lon.5deg,lfgrpd.stratflg)

# Loop to get all years' fishery estimates
for(year in yr.start:yr.end) {
  print(paste0("Year: ",year))
  
  print("Step 1: get well estimates")
  well.estimates <- well.estimates.7599.f(year)
  
  print("Step 2: get catch estimates")
  catch.estimates <- get.catch.estimates.7599.f(cae,cae.stratflg,corrected.unlds,lfgrpd,lfmm,year,2,well.estimates,PS)
  
  print("Step 3: get fishery estimates")
  fishery.estimates <- call.fishery.estimates.f(catch.estimates$stratum.estimates.withsamps,catch.estimates$totunlds.bystrat,year,PS)
  
  fishery.estimates.bet <- fishery.estimates$bet
  
  assign(paste0("fishery.estimates.", year), fishery.estimates.bet, pos=1)
}
save(list=objects(pat="fishery.estimates"),file=paste0(save_dir,"BET_",PS,"_1975-1999.RData"))

# get final catch and comp output for the stock assessment
BET.OBJ.Catch.20002021<-compile.catch.output.7599.f(yr.start,yr.end,PS=PS,Species=Species,c("A1","A2","A3","A4","A5"))
BET.OBJ.Comp.20002021<-compile.sizecomps.output.f(yr.start,yr.end,PS=PS,Species=Species)

# save results
write.csv(BET.OBJ.Catch.20002021,file=paste0(save_dir,"BET.OBJ.Catch.20002021.csv"),row.names = FALSE)
write.csv(BET.OBJ.Comp.20002021,file=paste0(save_dir,"BET.OBJ.Comp.20002021.csv"),row.names = FALSE)

# compare results
library(tidyverse)

BET_OBJ_Catch.SAC12 <- read.csv("D:/OneDrive - IATTC/IATTC/2022/BSE stuff from Cleridy/spp comp programs_from 2000/current_estimates/BET_FLOATING-OBJECT CATCH_FORMATTED_1975-2019_for SAC 2020.csv")
BET.OBJ.Catch.20002021 <- read.csv(paste0(save_dir,"BET.OBJ.Catch.20002021.csv"))

BET_OBJ_Catch.SAC12 <- BET_OBJ_Catch.SAC12[,2:8] %>% mutate(Source="Cleridy")
BET.OBJ.Catch.20002021 <- BET.OBJ.Catch.20002021 %>% mutate(Source="Haikun")

BET_OBJ_Catch <- rbind(BET_OBJ_Catch.SAC12,BET.OBJ.Catch.20002021) %>% 
  mutate(Year=year+quarter/4-1/8) %>%
  filter(year>1999,year<2020) %>%
  gather(3:7,key="Area",value="Catch")

ggplot(data=BET_OBJ_Catch) +
  geom_line(aes(x=Year,y=Catch,color=Source)) +
  facet_wrap(~Area,nrow=5) +
  theme_bw()

ggsave(file=paste0(save_dir,"BET.OBJ.Catch.png"),h=10,w=10)
